articles/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.articles, name='articles'),
    url(r'^write/$', views.write, name='write'),
    url(r'^draft/$', views.draft, name='draft'),
    url(r'^comment/(?P<article_id>[0-9]+)/$', views.comment, name='comment'),
    url(r'^tag/(?P<tag_name>.+)/$', views.tag, name='tag'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.edit, name='edit_article'),
    url(r'^(?P<slug>[-\w]+)/$', views.article, name='article'),
]

core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.settings, name='settings'),
    url(r'^password/$', views.password, name='password'),
    url(r'^picture/$', views.upload_picture, name='upload_picture'),
]

weforum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from core import views as core_views
from search import views as search_views
from authentication import views as authentication_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    url(r'^signup/$', authentication_views.signup, name='signup'),
    url(r'^login/$', auth_views.login, 
        {'template_name': 'core/cover.html', 'redirect_field_name': '/'}, name='login'),
    url(r'^logout/$', auth_views.logout, 
        {'next_page': '/'}, name='logout'),

    url(r'^articles/', include('articles.urls', namespace='articles')),
    url(r'^settings/', include('core.urls', namespace='core')),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^(?P<username>[0-9a-zA-Z_]+)/$', core_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/forms.py
from django import forms

from django.contrib.auth.models import User


class ProfileForm(forms.ModelForm):

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        label='First name',
        required=False)
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        label='Last name',
        required=False)
    job_title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        label='Job title',
        required=False)
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        label='Email',
        required=False)
    url = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        label='Url',
        required=False)
    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        label='Location',
        required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'job_title', 'email',
                  'url', 'location', ]


class ChangePasswordForm(forms.ModelForm):

    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Old password',
        required=True)
    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='New password',
        required=True)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Confirm new password',
        required=True)

    class Meta:
        model = User
        fields = ['id', 'old_password', 'new_password', 'confirm_password']

    def clean(self):
        super(ChangePasswordForm, self).clean()
        id = self.cleaned_data.get('id')
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            raise forms.ValidationError('Old password don\'t match')
        if new_password and new_password != confirm_password:
            raise forms.ValidationError('New password don\'t match')


class ProfileImageForm(forms.Form):
    image = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control'}),
        label='Select a image')

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from articles.views import articles, ARTICLES_NUM_PAGES
from articles.models import Article
from authentication.models import Profile
from .forms import ProfileForm, ChangePasswordForm, ProfileImageForm


def home(request):
    return articles(request)


@login_required
def profile(request, username):
    page_user = get_object_or_404(User, username=username)
    all_articles = page_user.article_set.filter(status=Article.PUBLISHED)
    paginator = Paginator(all_articles, ARTICLES_NUM_PAGES)
    articles = paginator.page(1)
    return render(request, 'core/profile.html', {
        'page_user': page_user,
        'articles': articles,
        'page': 1
    })


@login_required
def settings(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.email = form.cleaned_data.get('email')
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.profile.job_title = form.cleaned_data.get('job_title')
            user.profile.url = form.cleaned_data.get('url')
            user.profile.location = form.cleaned_data.get('location')
            user.save()
            user.profile.save()
            messages.add_message(request, 
                                 messages.SUCCESS, 
                                 'Your profile was successfully edited.')
            # return HttpResponseRedirect(reverse('profile', args=(user.username, )))

    else:
        form = ProfileForm(instance=user, initial={
            'job_title': user.profile.job_title,
            'url': user.profile.url,
            'location': user.profile.location
        })

    return render(request, 'core/settings.html', {'form': form})


@login_required
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, 
                                 messages.SUCCESS, 
                                 'Your password was successfully changed.')
            return HttpResponseRedirect(reverse('core:password'))

    else:
        form = ChangePasswordForm(instance=user)

    return render(request, 'core/password.html', {'form': form})


@login_required
def upload_picture(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = request.FILES.get('image')
            image.name = str(user.username) + '.jpg'
            user.profile.image = image
            user.profile.save()
            return HttpResponseRedirect(reverse('core:upload_picture'))

    else:
        form = ProfileImageForm()

    return render(request, 'core/picture.html', {'form': form})

core/templates/core/cover.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/cover.css' %}">
{% endblock head %}

{% block main %}
  <div class="cover">
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="login">
      <h2>登录</h2>
      <form method="post" action="{% url 'login' %}" role="form">
        {% csrf_token %}
        <div class="form-group{% if form.username.errors %} has-error{% endif %}">
          <label for="username">用户名</label>
          <input type="text" class="form-control" id="username" name="username">
          {% for error in form.username.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
          <label for="password">密码</label>
          <input type="password" class="form-control" id="password" name="password">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">登录</button>
          <a href="{% url 'signup' %}" class="btn btn-link">注册</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

core/templates/core/partial_settings_menu.html
<div class="list-group">
  <a href="{% url 'core:settings' %}" class="list-group-item{% if active == 'profile' %} active{% endif %}">账号资料</a>
  <a href="{% url 'core:upload_picture' %}" class="list-group-item{% if active == 'picture' %} active{% endif %}">账号头像</a>
  <a href="{% url 'core:password' %}" class="list-group-item{% if active == 'password' %} active{% endif %}">修改密码</a> 
</div>

core/templates/core/password.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}账号设置{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/settings.css' %}">
{% endblock %}

{% block main %}
<div class="settings">
  <div class="page-header">
    <h3>账号设置</h3>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-2">
      {% include 'core/partial_settings_menu.html' with active='password' %}
    </div>
    <div class="col-md-7">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      <form action="{% url 'core:password' %}" class="form-horizontal" method="post" role="form">
        {% csrf_token %}
        {{ form.id }}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-3 control-label">
              {{ field.label }}
            </label>
            <div class="col-sm-9">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label for="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary">保存</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

core/templates/core/picture.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}账号设置{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/settings.css' %}">
{% endblock %}

{% block main %}
<div class="settings">
  <div class="page-header">
    <h3>账号设置</h3>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-2">
      {% include 'core/partial_settings_menu.html' with active='picture' %}
    </div>
    <div class="col-md-7">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %} 
   
      <img src="{{ user.profile.get_picture }}" style="width: 150px; border-radius: 5px; margin-bottom: 1em;">
      <form enctype="multipart/form-data" method="post" action="{% url 'core:upload_picture' %}" id="picture-upload-form">
        {% csrf_token %}
        <div class="form-group">
        {{ form }}
        </div>
        <button type="submit" class="btn btn-default">保存</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

core/templates/core/profile.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} {{ page_user.profile.get_screen_name }} {% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block main %}

  <div class="profile">
    <div class="row">
      <div class="col-md-3 user-profile">
        <img src="{{ page_user.profile.get_picture }}" class="picture">
        <ul>
          {% if page_user.profile.job_title %}
            <li>
              <span class="glyphicon glyphicon-briefcase"></span> 
                {{ page_user.profile.job_title }}
            </li>
          {% endif %}
          {% if page_user.profile.location %}
            <li>
              <span class="glyphicon glyphicon-map-marker"></span> 
                {{ page_user.profile.location }}
            </li>
          {% endif %}
          {% if page_user.profile.url %}
            <li>
              <span class="glyphicon glyphicon-globe"></span> 
              <a href="{{ page_user.profile.get_url }}" target="_blank">
                {{ page_user.profile.get_url }}
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
      <div class="col-md-5">
        <h4>{{ page_user.profile.get_screen_name }}的最近发帖</h4><hr>
        <section class="articles">
        {% for article in articles %}
          <article>
            <h4>
              <a href="{% url 'articles:article' article.slug %}">
                {{ article.title }}
              </a>
            </h4>
            <div class="info">
            <span class="date">
              <span class="glyphicon glyphicon-calendar"></span>
                {{ article.create_date }}
            </span>
            <span class="user">
              <a href="#">
                <img src="{{ article.create_user.profile.get_picture }}">
              </a>
              <a href="#">{{ article.create_user.username }}</a>
            </span>
            <span class="comments">
              <span class="glyphicon glyphicon-comment"></span>
                {{ article.get_comments.count }} Comments
            </span>
            </div>
            <div class="content">
              {{ article.get_content_as_markdown|safe }}
            </div>
            {% if article.get_tags %}
              <div class="tags">
                {% for tag in article.get_tags %}
                  <a href="#">
                    <span class="label label-default">{{ tag }}</span>
                  </a>
                {% endfor %}
              </div>
            {% endif %}
          </article>  
        {% endfor %}        
        </section> 
      </div>
    </div>
  </div>
{% endblock %}

core/templates/core/settings.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}账号设置{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/settings.css' %}">
{% endblock %}

{% block main %}
<div class="settings">
  <div class="page-header">
    <h3>账号设置</h3>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-2">
      {% include 'core/partial_settings_menu.html' with active='profile' %}
    </div>
    <div class="col-md-7">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alter-dismissable ">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <form action="{% url 'core:settings' %}" role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">
              {{ field.label }}
            </label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">保存</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}