articles/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.articles, name='articles'),
    url(r'^write/$', views.write, name='write'),
    url(r'^draft/$', views.draft, name='draft'),
    url(r'^comment/(?P<article_id>[0-9]+)/$', views.comment, name='comment'),
    url(r'^tag/(?P<tag_name>.+)/$', views.tag, name='tag'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.edit, name='edit_article'),
    url(r'^(?P<slug>[-\w]+)/$', views.article, name='article'),
]

core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.settings, name='settings'),
    url(r'^password/$', views.password, name='password'),
    url(r'^picture/$', views.upload_picture, name='upload_picture'),
]

weforum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from core import views as core_views
from search import views as search_views
from authentication import views as authentication_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    url(r'^signup/$', authentication_views.signup, name='signup'),
    url(r'^login/$', auth_views.login, 
        {'template_name': 'core/cover.html', 'redirect_field_name': '/'}, name='login'),
    url(r'^logout/$', auth_views.logout, 
        {'next_page': '/'}, name='logout'),

    url(r'^articles/', include('articles.urls', namespace='articles')),
    url(r'^settings/', include('core.urls', namespace='core')),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^(?P<username>[0-9a-zA-Z_]+)/$', core_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from __future__ import unicode_literals

from datetime import datetime

import markdown

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Article(models.Model):
    DRAFT = 'D'
    PUBLISHED = 'P'
    STATUS = (
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=128, null=True, blank=True)
    content = models.TextField(max_length=4000)
    status = models.CharField(max_length=1, choices=STATUS, default=PUBLISHED)
    create_user = models.ForeignKey(User)
    create_date = models.DateTimeField(auto_now_add=True)
    update_user = models.ForeignKey(User, null=True, blank=True, related_name='+')
    update_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('-create_date', )

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            super(Article, self).save(*args, **kwargs)
        else:
            self.update_date = datetime.now()
        if not self.slug:
            slug_str = "%s %s" % (self.pk, self.title.lower())
            self.slug = slugify(slug_str)
        super(Article, self).save(*args, **kwargs)

    def get_content_as_markdown(self):
        return markdown.markdown(self.content, safe_mode='escape')

    @staticmethod
    def get_published():
        articles = Article.objects.filter(status=Article.PUBLISHED)
        return articles

    def create_tags(self, tags):
        tags = tags.strip()
        tag_list = tags.split(' ')
        for tag in tag_list:
            if tag:
                t, created = Tag.objects.get_or_create(tag=tag.lower(), 
                                                       article=self)

    def get_tags(self):
        return Tag.objects.filter(article=self)

    def get_summary(self):
        if len(self.content) > 100:
            return "{0}...".format(self.content[:100])
        else:
            return self.content

    def get_summary_as_markdowm(self):
        return markdown.markdown(self.get_summary(), safe_mode='escape')

    def get_comments(self):
        return ArticleComment.objects.filter(article=self)


class Tag(models.Model):
    article = models.ForeignKey(Article)
    tag = models.CharField(max_length=25)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        unique_together = (('tag', 'article'), )
        index_together = [['tag', 'article'], ]

    def __unicode__(self):
        return self.tag

    @staticmethod
    def get_popular_tags():
        tags = Tag.objects.all()
        count = {}
        for t in tags:
            if t.article.status == Article.PUBLISHED:
                if t.tag in count:
                    count[t.tag] = count[t.tag] + 1
                else:
                    count[t.tag] = 1
        sorted_tags = sorted(count.items(), key=lambda x: x[1], reverse=True)
        return sorted_tags[:10]


class ArticleComment(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Article)
    comment = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Article Comment'
        verbose_name_plural = 'Article Comments'
        ordering = ('-date', )

    def __unicode__(self):
        return "{0} - {1}".format(self.user.username, self.article.title)

articles/forms.py
from django import forms

from .models import Article


class ArticleForm(forms.ModelForm):
    
    status = forms.CharField(
        widget=forms.Select(attrs={'class:': 'form-control'}, choices=Article.STATUS), 
        initial=Article.PUBLISHED,
        max_length=1)
    # status = forms.CharField(widget=forms.HiddenInput())
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=100)
    content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        max_length=4000)
    tags = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=255, required=False,
        help_text='Use spaces to separate the tags.')

    class Meta:
        model = Article
        fields = ['title', 'content', 'tags', 'status']

articles/views.py
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Article, ArticleComment, Tag
from .forms import ArticleForm

ARTICLES_NUM_PAGES = 10


def _articles(request, articles):
    paginator = Paginator(articles, ARTICLES_NUM_PAGES)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    popular_tags = Tag.get_popular_tags()

    return render(request, 'articles/articles.html', {
        'articles': articles,
        'popular_tags': popular_tags,
    })


def articles(request):
    article_list = Article.get_published()
    return _articles(request, article_list)


def article(request, slug):
    article = get_object_or_404(Article, slug=slug, status=Article.PUBLISHED)
    return render(request, 'articles/article.html', {'article': article})


@login_required
def write(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = Article()
            article.create_user = request.user
            article.title = form.cleaned_data.get('title')
            article.content = form.cleaned_data.get('content')
            article.status = form.cleaned_data.get('status')
            article.save()
            tags = form.cleaned_data.get('tags')
            article.create_tags(tags)
            return HttpResponseRedirect(reverse('articles:articles'))

    else:
        form = ArticleForm()

    return render(request, 'articles/write.html', {'form': form})


def tag(request, tag_name):
    tags = get_list_or_404(Tag, tag=tag_name)
    articles = []
    for tag in tags:
        if tag.article.status == Article.PUBLISHED:
            articles.append(tag.article)

    return _articles(request, articles)


@login_required
def draft(request):
    draft_list = Article.objects.filter(create_user=request.user, 
                                        status=Article.DRAFT)
    return render(request, 'articles/draft.html', {'draft_list': draft_list})


@login_required
def edit(request, pk):
    tags = ''
    article = get_object_or_404(Article, pk=pk)

    if article.create_user.id != request.user.id:
        return HttpResponseRedirect(reverse('articles:articles'))

    for tag in article.get_tags():
        tags = '{0} {1}'.format(tags, tag.tag)
    tags = tags.strip()

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('articles:articles'))
    else:
        form = ArticleForm(instance=article, initial={'tags': tags})
    return render(request, 'articles/edit.html', {'form': form})


@login_required
def comment(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if request.method == 'POST':
        comment = request.POST.get('comment')
        comment = comment.strip()
        if len(comment) > 0:
            article_comment = ArticleComment(user=request.user, 
                                             article=article, 
                                             comment=comment)
            article_comment.save()
        return HttpResponseRedirect(reverse('articles:article', args=(article.slug, )))
    else:
        return render(request, 'articles/article.html', {'article': article})

articles/templates/articles/article.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ article.title }}{% endblock %}

{% block head %}
  <link href="{% static 'css/articles.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
<div class="col-md-7 article">
  <ol class="breadcrumb">
    <li><a href="{% url 'articles:articles' %}">首页</a></li>
    <li class="active">主题</li>
  </ol>
  {% include 'articles/partial_article.html' with article=article %}
  {% include 'articles/comments.html' with article=article %}
</div>
{% endblock main %}

articles/templates/articles/articles.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/articles.css' %}">
{% endblock %}

{% block main %}
  <div class="row">
    <div class="col-md-7">

      <div class="page-header">
        {% if user.is_authenticated %}
          <a href="{% url 'articles:write' %}" class="btn btn-default">
            <span class="glyphicon glyphicon-pencil"></span>发帖
          </a>
          <a href="{% url 'articles:draft' %}" class="btn btn-default" style="margin-right: .8em">草稿箱</a>
        {% endif %}
      </div>

      <section class="articles">
        {% for article in articles %}
          {% include 'articles/partial_article.html' with article=article %}
        {% empty %}
          <h5 class="no-data">还没有帖子发布<a href="#">来发布第一个帖子吧</a></h5>    
        {% endfor %}        
      </section>  
    </div>
    <div class="col-md-2 popular-tags">
      <h4>热门标签</h4>
      {% for tag, count in popular_tags %}
        <a href="{% url 'articles:tag' tag %}"><span class="label label-default">{{ tag }} {{ count }}</span></a>
      {% endfor %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      {% include 'paginator.html' with page=articles %}
    </div>
  </div>
{% endblock %}

articles/templates/articles/comments.html
{% load humanize %}
<hr>
<h4><span class="comment-count">{{ article.get_comments.count }}</span>
  评论
</h4>
{% if user.is_authenticated %}
<div class="post-comment clearfix">
  <form action="{% url 'articles:comment' article.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.pk }}">
    <div class="user-portrait clearfix">
      <img src="{{ user.profile.get_picture }}" alt="">
    </div>
    <div class="comment-input clearfix">
      <textarea name="comment" id="comment" rows="3" placeholder="发表评论" class="form-control"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">发表评论</button>
  </form>
</div>
{% endif %}
<div class="well well-sm" id="comment-list">
  {% for comment in article.get_comments %}
  <div class="comment">
    <a href="#"><img src="{{ comment.user.profile.get_picture }}" class="comment-portrait"></a>
    <div class="comment-text">
      <h5>
        <a href="#">{{ comment.user.username }}</a> 
        <small>{{ comment.date|naturaltime }}</small>
      </h5>
      <p>{{ comment.comment }}</p>
    </div>
  </div>  
  {% empty %}
    <div style="padding: .6em 0">还没有评论</div>
  {% endfor %}
</div>

articles/templates/articles/draft.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
  <link href="{% static 'css/write.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
<div class="write">
  <ol class="breadcrumb">
    <li><a href="{% url 'articles:articles' %}">首页</a></li>
    <li class="active"><a href="{% url 'articles:draft' %}">草稿箱</a></li>
  </ol>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>主题</th>
        <th>内容</th>
        <th>标签</th>
      </tr>
    </thead>
    <tbody>
      {% for article in draft_list %}
        <tr>
          <td>
            <a href="{% url 'articles:edit_article' article.pk %}">
              {{ article.title }}
            </a>
          </td>
          <td>{{ article.get_summary_as_markdowm|safe }}</td>
          <td>
            {% for tag in article.get_tags %}
              <span class="label label-default">{{ tag }}</span>
            {% endfor %}
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan='4' style="text-align: center">
            没有草稿
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

articles/templates/articles/edit.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main %}
<div class="col-md-8">
  <ol class="breadcrumb">
    <li><a href="{% url 'articles:articles' %}">首页</a></li>
    <li><a href="{% url 'articles:draft' %}">草稿箱</a></li>
    <li class="active">编辑</li>
  </ol>
  <form action="{% url 'articles:edit_article' form.instance.pk %}" method="post" role="form">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
        {{ field }}
        {% if field.help_text %}
          <span class="help-block">{{ field.help_text }}</span>
        {% endif %}
        {% for error in field.errors %}
          <label class="control-label">{{ error }}</label>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">发布/草稿箱</button>
  </form>
</div>
{% endblock %}

articles/templates/articles/partial_article.html
<article>
  <h4>
    <a href="{% url 'articles:article' article.slug %}">
      {{ article.title }}
    </a>
  </h4>
  <div class="info">
    <span class="date">
      <span class="glyphicon glyphicon-calendar"></span>
      {{ article.create_date }}
    </span>
    <span class="user">
      <a href="#"><img src="{{ article.create_user.profile.get_picture }}"></a>
      <a href="#">{{ article.create_user.username }}</a>
    </span>
    <span class="comments">
      <span class="glyphicon glyphicon-comment"></span>
      {{ article.get_comments.count }} Comments
    </span>
  </div>
  <div class="content">
    {{ article.get_content_as_markdown|safe }}
  </div>
  {% if article.get_tags %}
    <div class="tags">
      {% for tag in article.get_tags %}
        <a href="#"><span class="label label-default">{{ tag }}</span></a>
      {% endfor %}
    </div>
  {% endif %}
</article>

articles/templates/articles/write.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
  <link href="{% static 'css/write.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
<div class="col-md-8 write">
  <ol class="breadcrumb">
    <li><a href="{% url 'articles:articles' %}">首页</a></li>
    <li class="active">发帖</li>
  </ol>
  <form action="{% url 'articles:write' %}" method="post" role="form">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
        {{ field }}
        {% if field.help_text %}
          <span class="help-block">{{ field.help_text }}</span>
        {% endif %}
        {% for error in field.errors %}
          <label class="control-label">{{ error }}</label>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">发布/草稿箱</button>
  </form>
</div>
{% endblock %}