articles/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.articles, name='articles'),
    url(r'^write/$', views.write, name='write'),
    url(r'^draft/$', views.draft, name='draft'),
    url(r'^comment/(?P<article_id>[0-9]+)/$', views.comment, name='comment'),
    url(r'^tag/(?P<tag_name>.+)/$', views.tag, name='tag'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.edit, name='edit_article'),
    url(r'^(?P<slug>[-\w]+)/$', views.article, name='article'),
]

core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.settings, name='settings'),
    url(r'^password/$', views.password, name='password'),
    url(r'^picture/$', views.upload_picture, name='upload_picture'),
]

weforum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from core import views as core_views
from search import views as search_views
from authentication import views as authentication_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.home, name='home'),
    url(r'^signup/$', authentication_views.signup, name='signup'),
    url(r'^login/$', auth_views.login, 
        {'template_name': 'core/cover.html', 'redirect_field_name': '/'}, name='login'),
    url(r'^logout/$', auth_views.logout, 
        {'next_page': '/'}, name='logout'),

    url(r'^articles/', include('articles.urls', namespace='articles')),
    url(r'^settings/', include('core.urls', namespace='core')),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^(?P<username>[0-9a-zA-Z_]+)/$', core_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}WeForum{% endblock %}</title>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/weforum.css' %}">

    <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block head %}{% endblock %}
  </head>
  <body>
    {% block body %}
      <header>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'home' %}">WeForum</a>
            </div>

            <div class="collapse navbar-collapse" id="menu">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'articles:articles' %}">文章</a></li>
              </ul>

              <form action="{% url 'search' %}" class="navbar-form navbar-left" role="search">
                <div class="input-group">
                  <input type="text" class="form-control" name="q" placeholder="Search">
                  <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                  </span>
                </div>
              </form>

              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                  <li>
                    <a href="{% url 'profile' user.username %}"><img src="{{ user.profile.get_picture }}" class="user-img"></a>
                  </li>
                  <li>
                    <a href="{% url 'profile' user.username %}">{{ user.username }}</a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="#"><span class="badge pull-right" id="unread-count">0</span> 私信</a></li>
                      <li><a href="{% url 'core:settings' %}">用户设置</a></li>
                      <li class="divider"></li>
                      <li><a href="{% url 'logout' %}">退出登录</a></li>
                    </ul>
                  </li>
                {% else %}
                  <li><a href="{% url 'signup' %}">注册</a></li>
                  <li><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <div class="container">
          {% block main %}
          {% endblock %}
        </div>
      </main>
    {% endblock %}
  </body>
</html>

templates/paginator.html
<ul class="pagination">
  {% if page.has_previouns %}
    <li><a href="?page={{ page.previouns_page_number }}">&laquo;</a></li>
  {% else %}
    <li class="disabled"><span>&laquo;</span></li>
  {% endif %}
  {% for i in page.paginator.page_range %}
    {% if page.number == i %}
      <li class="active">
        <span>{{ i }}<span class="sr-only">(current)</span></span>
      </li>
    {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}
  {% if page.has_next %}
    <li><a href="?page={{ page.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="disabled"><span>&raquo;</span></li>
  {% endif %}
</ul>